spring:
  application:
    name: bookstore
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migrations
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpirationInSeconds: 86_400 #1 day
    refreshTokenExpirationInSeconds: 604_800 #7 days